/*flexberryautogenerated="true"*/
namespace IIS.InvestmentSystem
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;
    using System.Web.UI.WebControls;
    using ICSSoft.STORMNET.Web.AjaxControls;

    public partial class ПроектL : BaseListForm<Проект>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ПроектL() : base(Проект.Views.ПроектL)
        {
            EditPage = ПроектE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Proekt/ProektL.aspx"; }
        }

        public void RateButtonClick(object sender, ToolBarBtnEventArgs e)
        {
            if (e.PrimaryKeys.Count == 0)
                return;

            var pk = e.PrimaryKeys[0];
            Response.Redirect(Page.ResolveUrl(string.Format("~/forms/Proekt/RateProject.aspx?id={0}", pk)));
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            WebObjectListView1.PagesAtSide = false;
            WebObjectListView1.BottomPagerVisible = false;
            WebObjectListView1.Operations.SwitchNextPage = false;
            WebObjectListView1.Operations.ExportToExcel = false;
            WebObjectListView1.Operations.ExportToXML = false;
            WebObjectListView1.Operations.LimitEdit = false;
            WebObjectListView1.Operations.Filter = false;
            WebObjectListView1.Operations.Search = false;
            WebObjectListView1.AddImageButtonToRow("rateButton", "rate-button", "Оценить проект", RateButtonClick);
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
