/*flexberryautogenerated="true"*/
namespace IIS.Flexberry.Reports.Forms
{
    using System;
    using System.Linq;
    using System.Web.UI.WebControls;

    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Web.AjaxControls;
    using ICSSoft.STORMNET.Web.Controls;
    using ICSSoft.STORMNET.Web.Tools;

    using IIS.Flexberry.Reports.Core;
    using IIS.Flexberry.Reports.Core.Objects;

    public partial class ReportTemplateL : BaseListForm<ReportTemplate>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ReportTemplateL() : base(ReportTemplate.Views.ReportTemplateL)
        {
            EditPage = ReportTemplateE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Report/ReportTemplate/ReportTemplateL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
            ContextHelper.ПодключитьВнешнийФайл("/forms/Report/ReportTemplate/ReportTemplateL.js");
            WebObjectListView1.AddNewSeparator();
            WebObjectListView1.AddImageButton("btnGenerateReport", "btn-generate-report", "Построить отчет", "GenerateReportButtonClick", string.Empty);
            WebObjectListView1.AddImageButton("btnDesignReportTemplate", "btn-design-report", "Редактировать отчет", "DesignReportButtonClick", string.Empty);
        }



        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {

        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void btnDesignReportTemplate_Click(object sender, ToolBarBtnEventArgs e)
        {

            Response.Redirect(@"/StimulsoftReportTemplateEditor.aspx");
        }

        /// <summary>
        /// Обработчик кнопки запуска генерации отчета.
        /// </summary>
        /// <param name="sender">Инициатор события</param>
        /// <param name="e">Оргументы события</param>
        private void btnGenerateReportTemplate_Click(object sender, ToolBarBtnEventArgs e)
        {
            
            Response.Redirect(@"/StimulsoftReportTemplateEditor.aspx");
        }
    }
}
