<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="ModuleReportTemplateE.aspx.cs" Inherits="IIS.Flexberry.Reports.Forms.ModuleReportTemplateE" %>

<%-- Autogenerated section start [Register] --%>

<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-edit">
        <h2 class="ics-form-header ics-form-header-edit">Добавление шаблона отчёта на список</h2>
        <div class="ics-form-toolbar ics-form-toolbar-edit ics-sticky">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="ics-form-controls ics-form-controls-edit">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlReportTemplateLabel" runat="server" Text="Шаблон отчёта" EnableViewState="False">
</asp:Label>
<ac:MasterEditorAjaxLookUp ID="ctrlReportTemplate" CssClass="descTxt" runat="server" ShowInThickBox="True" Autocomplete="true" />

<asp:RequiredFieldValidator ID="ctrlReportTemplateValidator" runat="server" ControlToValidate="ctrlReportTemplate"
ErrorMessage="Не указано: ReportTemplate" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlReportTemplate_NameLabel" runat="server" Text="Название шаблона" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlReportTemplate_Name" runat="server" ReadOnly="true">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlReportTemplate_NameValidator" runat="server" ControlToValidate="ctrlReportTemplate_Name"
ErrorMessage="Не указано: ReportTemplate.Name" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlReportTemplate_DescriptionLabel" runat="server" Text="Описание шаблона" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlReportTemplate_Description" runat="server" ReadOnly="true">
</asp:TextBox>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlReportTemplate_OwnerLabel" runat="server" Text="Владелец шаблона" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlReportTemplate_Owner" runat="server" ReadOnly="true">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlReportTemplate_OwnerValidator" runat="server" ControlToValidate="ctrlReportTemplate_Owner"
ErrorMessage="Не указано: ReportTemplate.Owner" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlReportTemplate_IsSharedLabel" runat="server" Text="Общий шаблон" EnableViewState="False">
</asp:Label>
<asp:CheckBox ID="ctrlReportTemplate_IsShared" CssClass="descTxt" runat="server" Text="" Enabled="false"/>
</div>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
