/*flexberryautogenerated="true"*/
namespace IIS.Flexberry.Reports.Forms
{
    using ICSSoft.STORMNET.Web.Controls;
    using IIS.Flexberry.Reports.Core.Objects;

    public partial class ReportTypeL : BaseListForm<ReportType>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ReportTypeL() : base(ReportType.Views.ReportTypeL)
        {
            EditPage = ReportTypeE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Report/ReportType/ReportTypeL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
