<%--flexberryautogenerated="true"--%>
<%@ Page Language="C#" MasterPageFile="~/Site1.Master"  AutoEventWireup="true" CodeBehind="ReportTypeE.aspx.cs" Inherits="IIS.Flexberry.Reports.Forms.ReportTypeE" %>

<%-- Autogenerated section start [Register] --%>

<%-- Autogenerated section end [Register] --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="ics-form ics-form-edit">
        <h2 class="ics-form-header ics-form-header-edit">Тип отчёта</h2>
        <div class="ics-form-toolbar ics-form-toolbar-edit ics-sticky">
            <asp:ImageButton ID="SaveBtn" runat="server" SkinID="SaveBtn" OnClick="SaveBtn_Click" AlternateText="<%$ Resources: Resource, Save %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="SaveAndCloseBtn" runat="server" SkinID="SaveAndCloseBtn" OnClick="SaveAndCloseBtn_Click" AlternateText="<%$ Resources: Resource, Save_Close %>" ValidationGroup="savedoc" />
            <asp:ImageButton ID="CancelBtn" runat="server" SkinID="CancelBtn" OnClick="CancelBtn_Click" AlternateText="<%$ Resources: Resource, Cancel %>" />
        </div>
        <div class="ics-form-controls ics-form-controls-edit">
            <%-- Autogenerated section start [Controls] --%>
<!-- autogenerated start -->
<div>
	<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlNameLabel" runat="server" Text="Название" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlName" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlNameValidator" runat="server" ControlToValidate="ctrlName"
ErrorMessage="Не указано: Name" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlTypeNameLabel" runat="server" Text="Тип" EnableViewState="False">
</asp:Label>
<asp:TextBox CssClass="descTxt" ID="ctrlTypeName" runat="server">
</asp:TextBox>

<asp:RequiredFieldValidator ID="ctrlTypeNameValidator" runat="server" ControlToValidate="ctrlTypeName"
ErrorMessage="Не указано: TypeName" EnableClientScript="true" ValidationGroup="savedoc">*</asp:RequiredFieldValidator>

</div>
<div class="clearfix">
  <asp:Label CssClass="descLbl" ID="ctrlElementTypeLabel" runat="server" Text="Вид" EnableViewState="False">
</asp:Label>
<asp:DropDownList ID="ctrlElementType" CssClass="descTxt" runat="server">
	<asp:ListItem>Шаблон отчёта</asp:ListItem>
<asp:ListItem>Документ отчёта</asp:ListItem>

</asp:DropDownList>
</div>

</div>
<!-- autogenerated end -->
            <%-- Autogenerated section end [Controls] --%>
        </div>
    </div>
</asp:Content>
