//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.InvestmentSystem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Проект
    /// </summary>
    // *** Start programmer edit section *** (Проект CustomAttributes)

    // *** End programmer edit section *** (Проект CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПроектE", new string[] {
            "Название",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "НачальнаяИнвестиция as \'Начальная инвестиция\'",
            "Статус",
            "СтавкаДисконтирования as \'Ставка дисконтирования\'"})]
    [AssociatedDetailViewAttribute("ПроектE", "ЭлементДенежногоПотока", "ЭлементДенежногоПотокаD", true, "", "", true, new string[] {
            ""})]
    [View("ПроектL", new string[] {
            "Название",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Статус",
            "СтавкаДисконтирования as \'Ставка дисконтирования\'"})]
    public class Проект : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private System.DateTime fДатаОкончания;
        
        private IIS.InvestmentSystem.СтатусПроекта fСтатус;
        
        private decimal fНачальнаяИнвестиция;
        
        private decimal fСтавкаДисконтирования;
        
        private System.DateTime fДатаНачала;
        
        private IIS.InvestmentSystem.DetailArrayOfЭлементДенежногоПотока fЭлементДенежногоПотока;
        
        // *** Start programmer edit section *** (Проект CustomMembers)

        // *** End programmer edit section *** (Проект CustomMembers)

        
        /// <summary>
        /// Название
        /// </summary>
        // *** Start programmer edit section *** (Проект.Название CustomAttributes)

        // *** End programmer edit section *** (Проект.Название CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Название Get start)

                // *** End programmer edit section *** (Проект.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Проект.Название Get end)

                // *** End programmer edit section *** (Проект.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Название Set start)

                // *** End programmer edit section *** (Проект.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Проект.Название Set end)

                // *** End programmer edit section *** (Проект.Название Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания
        /// </summary>
        // *** Start programmer edit section *** (Проект.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (Проект.ДатаОкончания CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (Проект.ДатаОкончания Get start)

                // *** End programmer edit section *** (Проект.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (Проект.ДатаОкончания Get end)

                // *** End programmer edit section *** (Проект.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.ДатаОкончания Set start)

                // *** End programmer edit section *** (Проект.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (Проект.ДатаОкончания Set end)

                // *** End programmer edit section *** (Проект.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Статус
        /// </summary>
        // *** Start programmer edit section *** (Проект.Статус CustomAttributes)

        // *** End programmer edit section *** (Проект.Статус CustomAttributes)
        public virtual IIS.InvestmentSystem.СтатусПроекта Статус
        {
            get
            {
                // *** Start programmer edit section *** (Проект.Статус Get start)

                // *** End programmer edit section *** (Проект.Статус Get start)
                IIS.InvestmentSystem.СтатусПроекта result = this.fСтатус;
                // *** Start programmer edit section *** (Проект.Статус Get end)

                // *** End programmer edit section *** (Проект.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.Статус Set start)

                // *** End programmer edit section *** (Проект.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Проект.Статус Set end)

                // *** End programmer edit section *** (Проект.Статус Set end)
            }
        }
        
        /// <summary>
        /// НачальнаяИнвестиция
        /// </summary>
        // *** Start programmer edit section *** (Проект.НачальнаяИнвестиция CustomAttributes)

        // *** End programmer edit section *** (Проект.НачальнаяИнвестиция CustomAttributes)
        [NotNull()]
        public virtual decimal НачальнаяИнвестиция
        {
            get
            {
                // *** Start programmer edit section *** (Проект.НачальнаяИнвестиция Get start)

                // *** End programmer edit section *** (Проект.НачальнаяИнвестиция Get start)
                decimal result = this.fНачальнаяИнвестиция;
                // *** Start programmer edit section *** (Проект.НачальнаяИнвестиция Get end)

                // *** End programmer edit section *** (Проект.НачальнаяИнвестиция Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.НачальнаяИнвестиция Set start)

                // *** End programmer edit section *** (Проект.НачальнаяИнвестиция Set start)
                this.fНачальнаяИнвестиция = value;
                // *** Start programmer edit section *** (Проект.НачальнаяИнвестиция Set end)

                // *** End programmer edit section *** (Проект.НачальнаяИнвестиция Set end)
            }
        }
        
        /// <summary>
        /// СтавкаДисконтирования
        /// </summary>
        // *** Start programmer edit section *** (Проект.СтавкаДисконтирования CustomAttributes)

        // *** End programmer edit section *** (Проект.СтавкаДисконтирования CustomAttributes)
        [NotNull()]
        public virtual decimal СтавкаДисконтирования
        {
            get
            {
                // *** Start programmer edit section *** (Проект.СтавкаДисконтирования Get start)

                // *** End programmer edit section *** (Проект.СтавкаДисконтирования Get start)
                decimal result = this.fСтавкаДисконтирования;
                // *** Start programmer edit section *** (Проект.СтавкаДисконтирования Get end)

                // *** End programmer edit section *** (Проект.СтавкаДисконтирования Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.СтавкаДисконтирования Set start)

                // *** End programmer edit section *** (Проект.СтавкаДисконтирования Set start)
                this.fСтавкаДисконтирования = value;
                // *** Start programmer edit section *** (Проект.СтавкаДисконтирования Set end)

                // *** End programmer edit section *** (Проект.СтавкаДисконтирования Set end)
            }
        }
        
        /// <summary>
        /// ДатаНачала
        /// </summary>
        // *** Start programmer edit section *** (Проект.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (Проект.ДатаНачала CustomAttributes)
        [NotNull()]
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (Проект.ДатаНачала Get start)

                // *** End programmer edit section *** (Проект.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (Проект.ДатаНачала Get end)

                // *** End programmer edit section *** (Проект.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.ДатаНачала Set start)

                // *** End programmer edit section *** (Проект.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (Проект.ДатаНачала Set end)

                // *** End programmer edit section *** (Проект.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// Проект
        /// </summary>
        // *** Start programmer edit section *** (Проект.ЭлементДенежногоПотока CustomAttributes)

        // *** End programmer edit section *** (Проект.ЭлементДенежногоПотока CustomAttributes)
        public virtual IIS.InvestmentSystem.DetailArrayOfЭлементДенежногоПотока ЭлементДенежногоПотока
        {
            get
            {
                // *** Start programmer edit section *** (Проект.ЭлементДенежногоПотока Get start)

                // *** End programmer edit section *** (Проект.ЭлементДенежногоПотока Get start)
                if ((this.fЭлементДенежногоПотока == null))
                {
                    this.fЭлементДенежногоПотока = new IIS.InvestmentSystem.DetailArrayOfЭлементДенежногоПотока(this);
                }
                IIS.InvestmentSystem.DetailArrayOfЭлементДенежногоПотока result = this.fЭлементДенежногоПотока;
                // *** Start programmer edit section *** (Проект.ЭлементДенежногоПотока Get end)

                // *** End programmer edit section *** (Проект.ЭлементДенежногоПотока Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Проект.ЭлементДенежногоПотока Set start)

                // *** End programmer edit section *** (Проект.ЭлементДенежногоПотока Set start)
                this.fЭлементДенежногоПотока = value;
                // *** Start programmer edit section *** (Проект.ЭлементДенежногоПотока Set end)

                // *** End programmer edit section *** (Проект.ЭлементДенежногоПотока Set end)
            }
        }
        
        /// <summary>
        /// Class views container
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПроектE" view
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектE", typeof(IIS.InvestmentSystem.Проект));
                }
            }
            
            /// <summary>
            /// "ПроектL" view
            /// </summary>
            public static ICSSoft.STORMNET.View ПроектL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПроектL", typeof(IIS.InvestmentSystem.Проект));
                }
            }
        }
    }
}
