//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.InvestmentSystem
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус проекта
    /// </summary>
    // *** Start programmer edit section *** (СтатусПроекта CustomAttributes)

    // *** End programmer edit section *** (СтатусПроекта CustomAttributes)
    public enum СтатусПроекта
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусПроекта.Новый CustomAttributes)

        // *** End programmer edit section *** (СтатусПроекта.Новый CustomAttributes)
        Новый,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусПроекта.Принят CustomAttributes)

        // *** End programmer edit section *** (СтатусПроекта.Принят CustomAttributes)
        Принят,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (СтатусПроекта.Отклонен CustomAttributes)

        // *** End programmer edit section *** (СтатусПроекта.Отклонен CustomAttributes)
        Отклонен,
    }
}
