//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.InvestmentSystem
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип элемента денежного потока
    /// </summary>
    // *** Start programmer edit section *** (ТипЭлементаДенежногоПотока CustomAttributes)

    // *** End programmer edit section *** (ТипЭлементаДенежногоПотока CustomAttributes)
    public enum ТипЭлементаДенежногоПотока
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипЭлементаДенежногоПотока.Приток CustomAttributes)

        // *** End programmer edit section *** (ТипЭлементаДенежногоПотока.Приток CustomAttributes)
        Приток,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (ТипЭлементаДенежногоПотока.Отток CustomAttributes)

        // *** End programmer edit section *** (ТипЭлементаДенежногоПотока.Отток CustomAttributes)
        Отток,
    }
}
