//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.InvestmentSystem
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Элемент денежного потока
    /// </summary>
    // *** Start programmer edit section *** (ЭлементДенежногоПотока CustomAttributes)

    // *** End programmer edit section *** (ЭлементДенежногоПотока CustomAttributes)
    [AutoAltered()]
    [Caption("Элемент денежного потока")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЭлементДенежногоПотокаD", new string[] {
            "Дата",
            "Сумма",
            "Тип",
            "Проект"}, Hidden=new string[] {
            "Проект"})]
    public class ЭлементДенежногоПотока : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private decimal fСумма;
        
        private IIS.InvestmentSystem.ТипЭлементаДенежногоПотока fТип;
        
        private IIS.InvestmentSystem.Проект fПроект;
        
        // *** Start programmer edit section *** (ЭлементДенежногоПотока CustomMembers)

        // *** End programmer edit section *** (ЭлементДенежногоПотока CustomMembers)

        
        /// <summary>
        /// Дата
        /// </summary>
        // *** Start programmer edit section *** (ЭлементДенежногоПотока.Дата CustomAttributes)

        // *** End programmer edit section *** (ЭлементДенежногоПотока.Дата CustomAttributes)
        [NotNull()]
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Дата Get start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Дата Get end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Дата Set start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Дата Set end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Дата Set end)
            }
        }
        
        /// <summary>
        /// Сумма
        /// </summary>
        // *** Start programmer edit section *** (ЭлементДенежногоПотока.Сумма CustomAttributes)

        // *** End programmer edit section *** (ЭлементДенежногоПотока.Сумма CustomAttributes)
        [NotNull()]
        public virtual decimal Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Сумма Get start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Сумма Get start)
                decimal result = this.fСумма;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Сумма Get end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Сумма Set start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Сумма Set end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тип
        /// </summary>
        // *** Start programmer edit section *** (ЭлементДенежногоПотока.Тип CustomAttributes)

        // *** End programmer edit section *** (ЭлементДенежногоПотока.Тип CustomAttributes)
        [NotNull()]
        public virtual IIS.InvestmentSystem.ТипЭлементаДенежногоПотока Тип
        {
            get
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Тип Get start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Тип Get start)
                IIS.InvestmentSystem.ТипЭлементаДенежногоПотока result = this.fТип;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Тип Get end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Тип Set start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Тип Set end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.InvestmentSystem.Проект
        /// </summary>
        // *** Start programmer edit section *** (ЭлементДенежногоПотока.Проект CustomAttributes)

        // *** End programmer edit section *** (ЭлементДенежногоПотока.Проект CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Проект"})]
        public virtual IIS.InvestmentSystem.Проект Проект
        {
            get
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Проект Get start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Проект Get start)
                IIS.InvestmentSystem.Проект result = this.fПроект;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Проект Get end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Проект Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Проект Set start)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Проект Set start)
                this.fПроект = value;
                // *** Start programmer edit section *** (ЭлементДенежногоПотока.Проект Set end)

                // *** End programmer edit section *** (ЭлементДенежногоПотока.Проект Set end)
            }
        }
        
        /// <summary>
        /// Class views container
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЭлементДенежногоПотокаD" view
            /// </summary>
            public static ICSSoft.STORMNET.View ЭлементДенежногоПотокаD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭлементДенежногоПотокаD", typeof(IIS.InvestmentSystem.ЭлементДенежногоПотока));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЭлементДенежногоПотока
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЭлементДенежногоПотока CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЭлементДенежногоПотока CustomAttributes)
    public class DetailArrayOfЭлементДенежногоПотока : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.InvestmentSystem.DetailArrayOfЭлементДенежногоПотока members)

        // *** End programmer edit section *** (IIS.InvestmentSystem.DetailArrayOfЭлементДенежногоПотока members)

        
        /// <summary>
        /// Construct detail array
        /// </summary>
        public DetailArrayOfЭлементДенежногоПотока(IIS.InvestmentSystem.Проект fПроект) : 
                base(typeof(ЭлементДенежногоПотока), ((ICSSoft.STORMNET.DataObject)(fПроект)))
        {
        }
        
        /// <summary>
        /// Returns object with type ЭлементДенежногоПотока by index
        /// </summary>
        public IIS.InvestmentSystem.ЭлементДенежногоПотока this[int index]
        {
            get
            {
                return ((IIS.InvestmentSystem.ЭлементДенежногоПотока)(this.ItemByIndex(index)));
            }
        }
        
        /// <summary>
        /// Adds object with type ЭлементДенежногоПотока
        /// </summary>
        public virtual void Add(IIS.InvestmentSystem.ЭлементДенежногоПотока dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
